# Makefile for Raspberry Pi setup to make sure our file structure is correct
# Try to run the hello.bin program

# Default target
all: run

# Install the hello.bin program
run:
	pi-install hello.bin

# Clean target (optional)
clean:
	@echo "Nothing to clean"

.PHONY: all install clean